### ISSUE TITLE
multilevel wavelet and print DWT Scaling Coefficients

### ISSUE THREAD

**Issue by geraldstanje** [PyWavelets/pywt#174]
Hi,

How can I create a discrete wavelet with 8 levels and print the DWT Scaling Coefficients, like in the following example in R? http://ideone.com/h3oOqm

python:
```
N = 8
res = [2] * 256
w = pywt.Wavelet('haar')
res = pywt.wavedec(res, wavelet=w, mode='per', level=N)
print res
```

the python code only calculates level 8...is that expected? i only see one coefficient, which is 32

i did the following, but is there a way to avoid this loop? how can i set the max_level?
```
res = []

for i in range(1, 9):
  scaling_coeffs = pywt.wavedec(x, 'haar', level=i)
  res.append(scaling_coeffs[0][0])

print res
```

**Comment by kwohlfahrt** [comment]
The current behaviour is to only calculate the approximation coefficient at the highest level using `wavedec`. I think the wavelet packet module allows you to pick an arbitrary coefficient & level. I have not used it much in my work so I don't really know the details of it. I think this is correct:

```
wp = pywt.WaveletPacket(data, 'haar')
coeffs = [wp['a' * level].data for level in range(1, 9)]
```

If you do not want to use that, then using `dwt` on the previous scaling coefficient in your loop would be more efficient, since your method starts from the base level on each loop iteration:

```
data = [2] * 256
coeffs = [pywt.dwt(data, w, mode='per')[0]]
for i in range(1, 8):
  coeffs.append(pywt.dwt(coeffs[-1], w, mode='per')[0])
```

**Comment by kwohlfahrt** [comment]
Closing as solved. If the proposed solutions don't work, or you think there is a use-case for modifying the behaviour of `wavedec`, please comment and re-open.
