### ISSUE TITLE
swt_max_depth 

### ISSUE THREAD

**Issue by Mojusko** [PyWavelets/pywt#199]
The calculation results in 0 for an odd input, which cannot be correct.

**Comment by kwohlfahrt** [comment]
AFAIK, this is intentional behaviour. If possible, this is something we would like to improve, but this requires substantial work (it's not just a bug in `swt_max_depth`). It's been a while since I've looked, so perhaps somebody with more up to date knowledge could chime in.

Similarly, MATLAB (our reference implementation) does not support decomposition for arrays with a length that cannot be expressed as `2^N`.

**Comment by Mojusko** [comment]
The MATLAB remark is not correct. MATLAB accept any input size. One of the biggest advantages of modwt/swt is that it can be done on any input size. It is very unfortunate that this is the case and should be changed ASP IMHO.

**Comment by kwohlfahrt** [comment]
This is what I see (MATLAB R2016a) - is there another function that accepts other lengths, or is this available in a different version?

I agree it would be useful to add, but I'm not sure how the padding and filter upsampling would interact, especially without a reference to refer back to.

```
>> swc = swt([1, 2, 3, 4, 5, 6, 7], 1, 'db2')
 
*********************************************************************************************************************************************************************************************
ERROR ...
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 swt ---> The level of decomposition 1 and the length of the signal 7 are not compatible.
Suggested length: 8 (see Signal Extension Tool).

2^Level has to divide the length of the signal.
*********************************************************************************************************************************************************************************************
 

swc =

     []

>> swc = swt([1, 2, 3, 4, 5, 6, 7, 8], 1, 'db2')

swc =

   -1.0353   -0.0000   -0.0000   -0.0000   -0.0000   -0.0000    3.8637   -2.8284
    4.7603    2.3108    3.7250    5.1392    6.5534    7.9676   10.4171   10.0382

```

**Comment by kwohlfahrt** [comment]
I also just noticed that you referred to the MODWT - I think this is distinct from the SWT we implement, though I'm not 100% sure. There is some previous discussion in #51.

**Comment by Mojusko** [comment]
I am also not sure how exactly the algorithms work; I will have a look at it and possibly implement the modwt transform and submit a pull request. As for now the swt utility is more or less useless, and I would recommend using dft to everybody instead.

**Comment by kwohlfahrt** [comment]
@Mojusko contributions are always welcome! But please, calm down and do a bit of research before calling work useless or incorrect - your statement about MATLAB accepting arbitrary length input could have been checked in about 10 seconds. People have put their free time and hard work into this project and requests for speedups and new algorithms will be better received if they are made politely and/or with offers to help implement them.

Unless this is going to become an enhancement request to accept arbitrary length inputs for SWT, I'll close this in a day or two since `swt_max_depth` seems to be working as advertised.

**Comment by Mojusko** [comment]
@kwohlfahrt I meant my criticism in the best possible spirit. I apologize if I came across arrogantly. I value your and others work on this library and I have been using it for years!  

As for the SWT transform I really believe that it should be implemented as MODWT in Matlab or R as in current state one of the two major advantages of SWT/MODWT is not present. I will have a look into it and hopefully code up modwt module. You can tag this appropriately but I think it should stay in history of issues at least.

**Comment by kwohlfahrt** [comment]
No worries, easy to misunderstand things over text. Welcome aboard :)

MODWT has been in the feature queue for a while, so go ahead and grab it - there should be some useful links in #51, and further comments about it should go there. I'll make some suggestions there. The vote to close (not delete) this issue is therefore still up, as it is different.

**Comment by grlee77** [comment]
I believe the function you are referring to is `swt_max_level`?
I wouldn't consider it a bug, as what is returned matches the current implementation.  For `swt`, the size does not have to be a power of two, but it must be an integer multiple of `2**level`.

**Comment by rgommers** [comment]
Nothing to fix here, and possible improvement seems covered by gh-51. So agree with @kwohlfahrt that this issue can be closed.
