### ISSUE TITLE
No tests found from installed version

### ISSUE THREAD

**Issue by cdeil** [PyWavelets/pywt#280]
I added the Python 3.6 version of `pywt` to Macports just now: https://github.com/macports/macports-ports/pull/221

Installation seems to be OK, but no tests are found:
```
In [4]: pywt.test()
Running unit tests for pywt
NumPy version 1.12.0
NumPy relaxed strides checking option: True
NumPy is installed in /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy
Python version 3.6.0 (default, Dec 23 2016, 12:50:55) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
nose version 1.3.7

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Out[4]: <nose.result.TextTestResult run=0 errors=0 failures=0>
```

It should be possible to run tests for an installed version in `site-packages`, no?
It's very convenient to have for checking for users and packagers, not just devs from the source folder.

The docs aren't really clear on that point, whether it's supported: http://pywavelets.readthedocs.io/en/latest/dev/testing.html#running-tests-locally

Looks like there are no `test*` files installed in `site-packages`:
https://gist.github.com/cdeil/7362bd812fa372e98d1ce2270e798128

**Comment by rgommers** [comment]
That should indeed work, looks like a packaging issue. I thought we had CI set up for sdist/wheel to catch stuff like this, but apparently that's not the case. 

I'll try to fix this within a few days.

**Comment by grlee77** [comment]
@rgommers:  will you have a chance to work on this in the next week or so?  

It would be nice to have this fix along with the additional one in #289 for a 0.5.2 release.  I should have time to make a release next week.

**Comment by rgommers** [comment]
I'll try to have a go Saturday. Time is very limited though until the end of next week.

**Comment by rgommers** [comment]
Working on this now. The sdists on PyPI do have tests, but the wheels don't.

**Comment by rgommers** [comment]
The issue is that ``setuptools`` refuses to install ``.py`` files in sub-directories that do not have an ``__init__.py``. This used to be handled with `config.add_data_dir('tests')`` in ``setup.py`` files, but that got lost when getting rid of the dependency on ``numpy.distutils``.

The most straightforward solution is probably to add ``tests/__init__.py``. It does have some side effects though, will have to refresh my memory on those. Tests clearly isn't a submodule that should be importable, so the ``setuptools`` is conceptually wrong and ``numpy.distutils`` right (but what can you do ...).
