### ISSUE TITLE
WavletPacket2D constructor has no argument level

### ISSUE THREAD

**Issue by KrnTneja** [PyWavelets/pywt#319]
WavletPacket2D constructor when called as:

```
import pywt
import numpy as np
img = np.random.random((200, 200))
wp = pywt.WaveletPacket2D(img, wavelet='db1', level=
```
gives the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'level'
```
I tried with maxlevel argument instead of level, but when I check the level as:

`print(wp.level)`

The output is 0.

How are we supposed to take 2D Wavelet Packet Transform using pywt?

**Comment by grlee77** [comment]
`maxlevel` is the argument used to set the number of levels.  It may not be the most intuitive, but if you access a particular coefficient, the `level` attribute tells you what level of the decomposition it corresponds to.  For example for the code
```python
import pywt
import numpy as np
img = np.random.random((200, 200))
wp = pywt.WaveletPacket2D(img, wavelet='db1', maxlevel=2)
```

I have specified a maximum of 2 levels.  I can access via keys corresponding to the characters 'a', 'v', 'h', 'd', corresponding the approximation and various detail coefficients.  Repeated characters are used to access higher levels of decomposition (e.g. ['aa'] for the second level approximation coefficients)

`wp['h'].level` will be `1` (wp['h'] are the first level horizontal detail coefficients)
`wp['hv'].level` would be `2`.  
`wp['hhh'].level` would return an `IndexError` because the transform was called with `maxlevel=2`.

You can also see some examples of usage and plotting the various coefficients in this demo:
https://github.com/PyWavelets/pywt/blob/5d23d72e984025b792a25ab7284581b3afb0e4f0/demo/wp_2d.py

**Comment by grlee77** [comment]
Did you see `level` being used in the initializer somewhere in the documentation?  If so, that is an error we should fix.  

The [docs for the 2D wavelet packet](http://pywavelets.readthedocs.io/en/latest/ref/wavelet-packets.html#waveletpacket2d-and-waveletpacket2d-tree-node2d) class's `__init__`  list `maxlevel` as an optional argument which seems to be correct.

**Comment by KrnTneja** [comment]
No. Totally-my-bad. I didn't quite get the documentation (which is correct). 
I was hoping this to work like pywt.wavedec2 but now I get it.
