### ISSUE TITLE
http://wavelets.pybytes.com/ down

### ISSUE THREAD

**Issue by rgommers** [PyWavelets/pywt#323]
The wavelet browser is referenced from the PyWavelets docs, but the sources for and deployment code of that application are not in this repo. @nigma could you have a look at what is going on?

**Comment by grlee77** [comment]
I checked today an this seems to be back up again.

It is a separate issue that the wavelet list there is a bit outdated so that more recently added wavelets (e.g. `db21` to `db38`) are not listed.  Perhaps we should add a note in the docs that this site is no longer actively maintained or updated and does not reflect the full set of wavelets available.

**Comment by rgommers** [comment]
Adding that note makes sense to me.
