### ISSUE TITLE
how to reconstruct  DWT with same size?

### ISSUE THREAD

**Issue by maihao14** [PyWavelets/pywt#325]
I wanna the same results from Matlab code:
[C,L] = wavedec(data,5,'db4'); 
A = wrcoef('a',C,L,'db4',5);

How can I do this in pywt?
I noticed that  in pywt  use the certain group of coefficients  cA,cD cannot reconstruct the same size of the Original Data

**Comment by grlee77** [comment]
This is a little tricky because PyWavelets does not currently have an equivalent of the `wrcoef` function from Matlab.  An equivalent to that function can be implemented for 1D data by manually looping over calls to `pywt.upcoef`.  In the example below, `a` should end up equivalent to `A` in your Matlab code above: 

```python
import numpy as np
import pywt
data = np.arange(255.)
level = 5
c = pywt.wavedec(data, 'db4', level=level)

a, details = c[0], c[1:]
# size at each reconstruction level
L = [d.size for d in details[1:]] + [data.size, ]

for n in range(level):
    a = pywt.upcoef('a', a, 'db4', level=1, take=L[n])
```

**Comment by maihao14** [comment]
Thanks a lot.  It's very helpful for me to deal with this case.

**Comment by grlee77** [comment]
no problem.  In the future, please direct such questions to the mailing list at:
https://groups.google.com/forum/#!forum/pywavelets

This issue tracker is intended for reporting bugs in or discussing development of the source code.
