### ISSUE TITLE
run multithreaded / on the GPU

### ISSUE THREAD

**Issue by phdoerfler** [PyWavelets/pywt#371]
in my naive perspective it should not be too hard to run a wavelet transform with multiple threads or even on a GPU using OpenCL since it is an orthogonal transform and the individual pixels / coefficients are independent from each other.

Are there any plans on this?
I am asking because I am feeding large-ish images from DSLR cameras to pywavelets and I hate waiting these 1.6s to 2.2s for the `pywt.wavedec2`:

```
         226 function calls in 1.623 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    1.623    1.623 <string>:1(<module>)
        7    0.012    0.002    1.601    0.229 _multidim.py:113(dwtn)
       21    0.000    0.000    0.000    0.000 _multidim.py:168(<genexpr>)
        7    0.009    0.001    1.611    0.230 _multidim.py:22(dwt2)
        1    0.011    0.011    1.623    1.623 _multilevel.py:158(wavedec2)
        1    0.000    0.000    0.000    0.000 _multilevel.py:213(<listcomp>)
        1    0.000    0.000    0.001    0.001 _multilevel.py:26(_check_level)
        7    0.000    0.000    0.001    0.000 arraysetops.py:113(unique)
        7    0.000    0.000    0.001    0.000 arraysetops.py:256(_unique1d)
       15    0.000    0.000    0.000    0.000 numeric.py:424(asarray)
       14    0.000    0.000    0.000    0.000 numeric.py:495(asanyarray)
        7    0.000    0.000    0.000    0.000 type_check.py:250(iscomplexobj)
        1    0.000    0.000    1.623    1.623 {built-in method builtins.exec}
        8    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
        7    0.000    0.000    0.000    0.000 {built-in method builtins.issubclass}
       17    0.000    0.000    0.000    0.000 {built-in method builtins.len}
        1    0.000    0.000    0.000    0.000 {built-in method builtins.min}
       29    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.array}
        7    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.concatenate}
       21    1.589    0.076    1.589    0.076 {built-in method pywt._extensions._dwt.dwt_axis}
        1    0.001    0.001    0.001    0.001 {built-in method pywt._extensions._dwt.dwt_max_level}
        8    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
       21    0.000    0.000    0.000    0.000 {method 'extend' of 'list' objects}
        7    0.000    0.000    0.000    0.000 {method 'flatten' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.000    0.000 {method 'reverse' of 'list' objects}
        7    0.001    0.000    0.001    0.000 {method 'sort' of 'numpy.ndarray' objects}
```

How can I make this faster?

Doesn't pywavelets ultimately rely on numpy? Is there no GPU support for numpy? Am I asking too much?

**Comment by grlee77** [comment]
It is in principle possible to run multi-threaded on the CPU, but performance can be memory bound so that a naive parallel loop over the pixels doesn't seem to work very well.   At the moment each transform runs in a single thread, but you can run multiple images in parallel for batch processing.  See:
https://github.com/PyWavelets/pywt/blob/master/demo/batch_processing.py

You might also look at [PDWT](https://github.com/pierrepaleo/PDWT) which is implemented in Python + CUDA.  It uses wavelet coefficients borrowed from PyWavelets and supports 1D and 2D transforms on the GPU. For large enough images the GPU implementation should be faster than PyWavelets. For small images the overhead of transferring data to/from the GPU will make it slower.

The [libdwt](https://github.com/xbarin02/libdwt) library and associated publications have compared a number of potential CPU implementations exploiting multi-threading in combination with SIMD. That library is not in Python and is more limited in the range of wavelets and transforms supported, but should have higher performance.  However, this comes at cost of substantially increased complexity in the implementation.

> Doesn't pywavelets ultimately rely on numpy?

Although PyWavelets does rely on numpy, the bulk of the computation is done by C code for down-sample d or up-sampled convolutions that is included with PyWavelets itself. C code is in:
https://github.com/PyWavelets/pywt/tree/master/pywt/_extensions/c
and Cython code in
https://github.com/PyWavelets/pywt/tree/master/pywt/_extensions

Numpy itself does not have GPU support.  Some other libraries such as [CuPy](https://github.com/cupy/cupy) and [PyCUDA](tps://mathema.tician.de/software/pycuda/) provide numpy-like GPU arrays.  You cannot pass these GPU arrays to any of the functions in PyWavelets, though.

**Comment by phdoerfler** [comment]
Thanks for the great write-up, I'll check those links out!
