### ISSUE TITLE
How to Use PyWavelet on EEG Signal

### ISSUE THREAD

**Issue by lampsoft** [PyWavelets/pywt#374]
Dear All,

My thesis is on Classification of EEG signals using Wavelet Transform and Artificial  Immune Recognition System.
 I have  5 dataset  EEG with each containing 100x4098 data (csv)
I'm really confused as I don't how to use PyWavelet in Python to both decompose and feature to extract and select from this data.  I've check Youtube to see how PyWavelet but I couldn't find.
I want to use python for the project though I'm newbie to Python Programming Lang.....!
My question is how can I upload my csv file on dwt?? for both feature selection, decomposition and extraction???

Also from all I have read in Python Machine learning I haven't come across any Artificial Immune Recognition System Algorithm been use.... Unlike ANN that has sklearn and keras.... Non is available for AIS... Please Can you put me through this project! I really need your help! Thanks!

Thanks!

**Comment by grlee77** [comment]
General questions such as this are better suited to the google group at https://groups.google.com/forum/#!forum/pywavelets . This issues page is for bug reports, feature requests, etc.

You can read from CSV files with a function such as NumPy's `genfromtxt` with the argument `delimiter=','`.  There are is also a nice function for CSV reading implemented in [Pandas](http://pandas.pydata.org/pandas-docs/stable/io.html).

Once you have the data stored as a NumPy array, you can use the functions in PyWavelets to do either single-level (e.g. `pywt.dwt`) or multi-level (e.g. `pywt.wavedec`) wavelet transforms.  There is nothing built into PyWavelets for feature selection/extraction so that is something you would need to implement for your project.

**Comment by kwohlfahrt** [comment]
Sorry my bad - I got an email and sent him here.
