### ISSUE TITLE
set wavelet parameters for cwt

### ISSUE THREAD

**Issue by ggrrll** [PyWavelets/pywt#388]
Hi, 

it doesn't seem very clear [in the doc](http://pywavelets.readthedocs.io/en/latest/ref/cwt.html) how to set the wavelet parameters for `cwt` -- passing for instance `cmorB-C` does not work as not included in `pywt.wavelist` 

Thanks

**Comment by grlee77** [comment]
The documentation gets built from the master branch here rather than the last release. In version 0.5.2 it was not possible to include the center frequency or bandwith in the name. 

The workaround in 0.5.2 is to first generate the wavelet and then set the attributes afterwards:
```python
wav = pywt.ContinuousWavelet('cmor')
wav.center_frequency = 0.5
wav.bandwidth_frequency = 3.0
```

In the next release it will be possible to instead just call:
```python
wav = pywt.ContinuousWavelet('cmor3.0-0.5')
```

You would have to build from source to get the new capability. @rgommers and I made some plans to push toward a 1.0 release within the next month or so, but we didn't set an explicit date.

**Comment by grlee77** [comment]
closing as this feature was released and now [shows up in the docs](https://pywavelets.readthedocs.io/en/latest/ref/cwt.html#complex-morlet-wavelets)
