### ISSUE TITLE
RMS from wavelet coefficients

### ISSUE THREAD

**Issue by shabela** [PyWavelets/pywt#429]
Hello, I have a question 

I cross posted this question on DSP-exchange (https://dsp.stackexchange.com/questions/52213/rms-value-from-wavelet-coefficients)
```

import numpy as np
import pywt
a = 1
fs = 16
f = 1
y = a*np.sin(2*np.pi* f * np.linspace(0, 1, fs))
rms = np.sqrt(np.mean(np.square(y)))
rms_theory = a/2**0.5
print(rms , rms_theory)

"""
0.6846531968814576 0.7071067811865475
"""

c = pywt.wavedec(y, 'db1')

"""
wavelet coefficients 'c'

+0.0000  
+2.3786  
-0.1963  -0.1963  
-0.6437  +0.5324  +0.5324  -0.6437  
-0.2876  -0.1470  +0.0909  +0.2686  +0.2686  +0.0909  -0.1470  -0.2876  
"""

```

How do I calculate rms from wavelet coefficients alone? I searched quite a number of papers, but I am confused about the $d_j^i[k]$ notation (see, e.g., [this paper](https://www.jstage.jst.go.jp/article/ieejpes1990/122/5/122_5_599/_pdf))

Can anybody show me a snippet of code? Thanks

**Comment by grlee77** [comment]
The paper you cited is using the wavelet packet transform (available via the `pywt.WaveletPacket` class) rather than the standard DWT used by `pywt.wavedec`. The difference is that the packet transform continues to filter the detail coefficients at each level of the decomposition.

I did not read the paper, but the notation used in Fig. 1 indicates that the superscripts just enumerate the different coefficients available at each level of the transform while the subscript subscripts indicates the level of decomposition. So a pair `(i, j)` defines which coefficient array we are working with and `k` is just the index into that coefficient array.

The filters `h` and `g` in the paper correspond to the lowpass and highpass filters, respectively. In the `pywt.WaveletPacket` implementation, applying `h` corresponds to the character `'a'`, while applying filter `g` corresponds to the character `'d'`.
So to access the filter d^2_2 from Fig. 1 you need to select the coefficients that result from highpass filtering ('d') followed by lowpass filtering ('a'). This is done by indexing the wavelet packet object with index `['da']`.
