### ISSUE TITLE
waverec after wavedec

### ISSUE THREAD

**Issue by BCIstorm** [PyWavelets/pywt#432]
Hello, I'm new to Pywt and I'm trying to perform some signal cleaning zero-ing one of the components of the decomposition. Here is the simple example code:

`wfname = "db4" #wavelet family name`
`coeffs = pywt.wavedec(original_signal, wfname, level=2)`

`coeffs[0] = np.zeros_like(coeffs[0]) #zeroing this coefficient`
`signal_filtered = pywt.waverec(coeffs, wfname)`

The problem is that the `filtered_signal` has different size than `original_signal`, respectively `(151L,)` vs `(152L,)` both `float64`.
  Can someone spot why and to fix it?

**Comment by grlee77** [comment]
Hi,

The original signal is size 151 and reconstructed is 152? That can happen
due to how the signal edges are handled. The inverse transform does not
know the original signal size. You can just discard the one extra sample
from the end.

To verify this is correct you can check running wavedec then waverec
without the thresholding and you should get back the original signal.

**Comment by BCIstorm** [comment]
Thank you for the answer @grlee77 .
