### ISSUE TITLE
Batch load for pywt.cwt

### ISSUE THREAD

**Issue by SongRb** [PyWavelets/pywt#445]
I'm working on a machine learning application and have to do transformation on large scale of data. I want to call the function like `pywt.cwt((batch_size, signal_length))`, but it seems only `dim=1` supported. Is there any plan for supporting this feature?

**Comment by grlee77** [comment]
Hi @SongRb:

An implementation of this has been proposed in #509.

Any feedback there would be welcome. In the case of data with shape `(batch_size, signal_length)`, you could leave the default `axis=-1` argument since the signal is along the last axis of the input. The output would have shape `(len(scales), batch_size, signal_length)`.

Also, another recent PR allows setting `mode='fft'` to do FFT-based convolutions for the CWT. This should have a performance benefit for larger data / scales.
