### ISSUE TITLE
iswtn error when using axes and excluded dim is desn't comply to the level

### ISSUE THREAD

**Issue by Obi-Wan** [PyWavelets/pywt#460]
Hi, I get an error when trying to compute the inverse SWT of an array with dimensions of size different from 2 ** wavelet_level, even if they are being excluded through the 'axes' keyword.

Here is an example:
`test_vec = np.random.rand(1, 32, 32)`
`test_vec_swt = pywt.swtn(test_vec, 'db1', 3, axes=(1, 2))`
`test_vec_iswt = pywt.iswtn(test_vec_swt, 'db1', axes=(1, 2))`

The last line returns the following error:

> Traceback (most recent call last):
> 
>   File "<ipython-input-33-107e5e20d0fc>", line 1, in <module>
>     test_vec_iswt = pywt.iswtn(test_vec_swt, 'db1', axes=(1, 2))
> 
>   File "/ufs/vigano/miniconda3/lib/python3.7/site-packages/pywt/_swt.py", line 529, in iswtn
>     output[tuple(indices)] += x
> 
> ValueError: non-broadcastable output operand with shape (1,1,8) doesn't match the broadcast shape (1,2,8)

The error does not happen if the array has for instance shape (8, 32, 32), or if using dwtn / idwtn.

**Comment by grlee77** [comment]
Thanks for reporting this. I will take a look later today.

**Comment by grlee77** [comment]
I have confirmed this bug. It can be fixed by replacing the following line:

https://github.com/PyWavelets/pywt/blob/dbdd4beb42d3a247211fa20faae08b207d4f0b58/pywt/_swt.py#L521

with:
```Python
dshape = tuple([shapes[0][ax] for ax in axes])
```

I will make a pull request with this fix and a test case for it.  We are planning to do a bug fix release soon, but in the meantime you can modify `_swt.py` as above in your local copy.

**Comment by Obi-Wan** [comment]
Thank you very much! :+1:
