### ISSUE TITLE
Should threshold accept multiple 1-D wavelets?

### ISSUE THREAD

**Issue by RoMa03** [PyWavelets/pywt#461]
```
test = np.arange(16).reshape(2,8)
wav = pywt.wavedec(test, 'haar', mode='periodization', level=None, axis=-1)
#wav = pywt.threshold(wav, 3, mode='hard')
recon = pywt.waverec(wav, 'haar', mode='periodization', axis=-1)
```

The above code runs as I expect, constructing a 1-D wavelet decomposition for each of 2 series and then reconstructing the original series from them.  However if the '#' is removed, the result is "ValueError: could not broadcast input array from shape (2,1) into shape (2)".  I am not very familiar with the package but this seems strange?

**Comment by grlee77** [comment]
The threshold functions do operate on arrays in any number of dimensions.  There error in your case is because you were passing in a list of arrays as returned by `wavedec` instead of a single array. You would need to call threshold on each individual array.  Assuming you intended to apply this same hard threshold to all levels of coefficients, you would need to replace your commented line with:
```python
wav = [pywt.threshold(arr, 3, 'hard') for arr in wav]
```

A more detailed example with automatic determination of threshold levels and potentially variable thresholds across coefficients can be seen in the [_wavelet_threshold method](https://github.com/scikit-image/scikit-image/blob/e9cf8b850c4c2800cc221be6f1dfff6a2a32a4eb/skimage/restoration/_denoise.py#L380-L491) used for denoising in scikit-image.

**Comment by RoMa03** [comment]
Thank you for your clear explanation and suggestions.  

I do want to apply a fixed threshold to a large set of equal-length vectors.  It seems a little counter-intuitive to have to loop through each vector, but perhaps my application is unusual.

**Comment by grlee77** [comment]
I suspect your application is not uncommon.

In principle, the thresholding functions could accept lists of coefficients, however each of the different transforms (`wavedecn`, `swtn`, `fswavedecn`, etc) have a different coefficient format. Handling all of these within the thresholding functions would add quite a bit of complexity.

**Comment by rgommers** [comment]
The question is answered, so I'll close this issue.
