### ISSUE TITLE
Get specific coefficient from wavedec

### ISSUE THREAD

**Issue by hndr91** [PyWavelets/pywt#501]
I've read the documentation and the code. I can't find function that similiar to **detcoef** for 1D signal by matlab wavelet toolbox. Is it possible to add this function to PyWavelet ? I think sometimes We only need to get spectific coefficient. I've made this function for my own purpuse and willing to PR, but I'm still not sure if my function is correct or not.

**Comment by grlee77** [comment]
Matlab has that function because the coefficients from Matlab's `wavedec` get returned as a single contiguous array and that function helps extract the ones corresponding to a particular level.

In PyWavelets, a list of coefficients is already returned. See the description of the output format [here](https://pywavelets.readthedocs.io/en/latest/ref/dwt-discrete-wavelet-transform.html#multilevel-decomposition-using-wavedec). So, the level `n` detail coefficients are just `c[-n]` (where ``c = wavedec(x, wavelet)``). I don't think it is worth adding a trivial function such as:
```Python
def detcoef(c, n):
    return c[-n]
```

If you do want a single array format in PyWavelets rather than the lists of arrays, see the functions `ravel_coeffs` and `unravel_coeffs` which [convert to/from that type of format](https://pywavelets.readthedocs.io/en/latest/ref/dwt-coefficient-handling.html#raveling-and-unraveling-coefficients-to-from-a-1d-array).

**Comment by hndr91** [comment]
thanks @grlee77 , I think your are right. Detcoef not worthed in this case even we return multiple coefficients.
