### ISSUE TITLE
i no find the function of pad

### ISSUE THREAD

**Issue by fish-galaxy** [PyWavelets/pywt#524]
is it common issue?

**Comment by grlee77** [comment]
`pad` is an upcoming feature for release 1.1 and should be available soon. It is available now if you build checkout the master branch here and build from source.  We intend to tag an official release 1.1 and put it up on pypi and conda-forge soon.

The default at `readthedocs` is to point to the documentation of the development version rather than the latest release. This sometimes causes confusion for users, so I'm not sure if it might be better to just default to showing the latest release on `readthedocs`. If you select the documentation for our last official release (1.0.3) you should not see the `pad` function listed there.
