### ISSUE TITLE
WaveletPacket，How can I calculate the frequency range of each node in layer 3

### ISSUE THREAD

**Issue by yanwencheng** [PyWavelets/pywt#551]
wp = pywt.WaveletPacket(data=data_reshape, wavelet='db1', mode='symmetric', maxlevel=3)

How can I calculate the frequency range of each node in layer 3

**Comment by grlee77** [comment]
If you use `wp.get_level(3, order="freq")` you will get a list of the nodes ordered from the lowest to highest frequency content. There will be some overlap in frequency content between the packets because the wavelet filters are not band-limited, but each should be concentrated in a frequency band of width of ``BW/N`` where ``N=2**level`` is the number of nodes at a given level and BW is the bandwidth of the original signal.

The details of the wavelet packet ordering is at first somewhat non-intuitive due to aliasing effects. We don't have detailed documentation on this here, but it is covered in Wickerhauser's text and there are some nice figures in [Matlab's documentation](https://www.mathworks.com/help/wavelet/ug/wavelet-packets.html#f8-22400).

**Comment by wu5625520** [comment]
Hello, if I input a signal, how does the function determine the BW（ BW is the bandwidth of the original signal）of the signal？

**Comment by rgommers** [comment]
Question is answered, I'll close this issue.
