### ISSUE TITLE
SWT2 with db4 error

### ISSUE THREAD

**Issue by cavrinceanu** [PyWavelets/pywt#592]
Hi! Not an issue in itself I guess (might be), but I am posting here because so far I cannot find a solution to this, even though I searched StackOverflow and the PYWT forum. I am trying to apply swt2 with a db4 decomposition to an (516, 862) 2D array. The data has been padded to meet the 2**level criteria and the max level has been calculated to be 3 using swt_max_level. My need is to extract the coefficients at each level (up to max_level), however I when the level > 1 I keep receiving the start_level must be less than 1 error, even though I specifically declare it to be 0. Am I missing something?

**Comment by grlee77** [comment]
> has been padded to meet the 2**level criteria

This should work. If I want to do a 3-level decomposition of data that is shape (516, 862) then it needs to be padded to a multiple of 2**3 on each axis. So, the padded shape should be `(516, 864)` in this case.

The following works for me. 
```Python
import numpy as np
import pywt

x = np.random.randn(516, 862)
x_pad = np.pad(x, pad_width=((0, 0), (0, 2)), mode='reflect')
y = pywt.swt(x_pad, wavelet='db4', level=3)
```

If you are not padding as above, it is expected that the max level will be one since 862 is divisible by 2**1, but not 2**2

If you are still seeing a problem, can you paste the script similar to the example above that reproduces the issue?

**Comment by cavrinceanu** [comment]
Ohhhh, nooo, this was so obvious. I padded the signal but to consider the 2*n not the exponent. So much in my face. Code's fine and thanks so much! Sometimes all it takes is a clear mind to point it out to you after spending to much time on it.

**Comment by grlee77** [comment]
Great, glad it is working now.
