### ISSUE TITLE
inverse wavelet packet transform

### ISSUE THREAD

**Issue by apznv** [PyWavelets/pywt#615]
Hi everyone, I am working on wavelet transform OFDM. For that, I want to do an Inverse wavelet packet transform of the data at the transmitter. However, IWPT depends on DWPT in matlab. is there any option to do IDWPT without doing dwpt in python.
please help
APZnv

**Comment by rgommers** [comment]
You're going to have to be a little more specific about what your actual problem is. Are you talking about the inverse for wavelet _packet_ transforms (i.e. the `reconstruct` method on one of the classes in https://pywavelets.readthedocs.io/en/latest/ref/wavelet-packets.html)? Please provide an actual code example if you can.

**Comment by apznv** [comment]
Hi rgommers,
I am trying to model the OFDM system using Wavelet Transform. At the transmitter, I have to use inverse wavelet packet transform of the modulated data which is complex in nature. On the receiver side, I will use DWPT. I tried to generate the code using Matlab. But it is not working. In Matlab to generate IDWPT, we need an index vector that I don't have.
reconstruction and decomposition work on the tree structure.  SO confused,,,,,
Thank you very much in advance,
Regards
apznv

**Comment by rgommers** [comment]
I'm sorry, we (the maintainers) have extremely limited bandwidth to work on this package, and can't answer questions like these.
